version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "org.springframework.boot:spring-boot-maven-plugin"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(deps)"
