name: CheckPullRequest

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  delete-comments:
    name: Delete bot comment(s)
    runs-on: ubuntu-latest
    steps:
      - uses: izhangzhihao/delete-comment@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          delete_user_name: github-actions[bot]
          issue_number: ${{ github.event.number }}

  branch-naming-rules:
    name: Check branch name
    runs-on: ubuntu-latest
    steps:
      - uses: deepakputhraya/action-branch-name@master
        with:
          regex: '^(feature|bugfix|improvement|library|prerelease|release|hotfix)\/[a-z0-9_.-]+$|^dependabot\/.+$'
          allowed_prefixes: 'feature,bugfix,improvement,library,prerelease,release,hotfix,dependabot'
          ignore: main
          min_length: 5
          max_length: 50
